version: '3'

services:

  cw:
    image: beefbytes/cubeworld
    container_name: cubeworld_server
    stdin_open: true
    tty: true
    volumes:
      - ${DATA_DIR}/config:/mnt/cuwo/config
      - ${DATA_DIR}/logs:/mnt/cuwo/logs
      - ${DATA_DIR}/data:/mnt/cuwo/data
      - ${DATA_DIR}/save:/mnt/cuwo/save
    ports:
      - 12345:12345